name: Publish Billing Yard to PyPI
on: push

jobs:
  build:
    name: Build Python packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '>=3.9'
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the packages
          uses: actions/upload-artifact@v4
          with:
            name: billing-yard
            path: dist/